version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===== Build Tasks =====

  build:web:
    desc: Build TypeScript/web frontend
    dir: web
    cmds:
      - bun run build

  build:tauri:
    desc: Build Tauri desktop app
    deps: [build:web]
    cmds:
      - cd src-tauri && cargo build --release

  build:all:
    desc: Build web and Tauri
    deps: [build:web, build:tauri]

  # ===== Test Tasks =====

  test:web:
    desc: Run TypeScript/web tests
    dir: web
    cmds:
      - bun run test:run

  test:e2e:
    desc: Run Playwright end-to-end tests
    dir: web
    cmds:
      - bun run test:e2e

  test:e2e:headed:
    desc: Run Playwright E2E tests with browser visible
    dir: web
    cmds:
      - bun run test:e2e:headed

  test:e2e:ui:
    desc: Run Playwright E2E tests with UI mode
    dir: web
    cmds:
      - bun run test:e2e:ui

  test:
    desc: Run all tests
    cmds:
      - task: test:web

  # ===== Development Tasks =====

  dev:web:
    desc: Start web dev server with hot reload
    dir: web
    cmds:
      - bun run dev

  dev:tauri:
    desc: Start Tauri dev mode
    cmds:
      - cd src-tauri && cargo tauri dev

  dev:
    desc: Start development (alias for dev:tauri)
    cmds:
      - task: dev:tauri

  run:app:
    desc: Run the desktop app (debug mode, default)
    cmds:
      - cargo tauri dev

  run:app:debug:
    desc: Run the desktop app in debug mode (alias for run:app)
    cmds:
      - task: run:app

  run:app:release:
    desc: Build and run the desktop app in release mode (bundled with icons)
    deps: [build:web]
    cmds:
      - cd src-tauri && cargo tauri build
      - open ./src-tauri/target/release/bundle/macos/pastel-hn.app

  # ===== Format & Lint Tasks =====

  fmt:web:
    desc: Format TypeScript/web code
    dir: web
    cmds:
      - bunx biome check --write --unsafe src/

  fmt:
    desc: Format all code
    cmds:
      - task: fmt:web

  fmt:check:
    desc: Check formatting (CI-friendly)
    cmds:
      - cd web && bunx biome check src/

  lint:
    desc: Lint all code
    cmds:
      - cd web && bunx biome lint src/

  # ===== Clean Tasks =====

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf web/dist
      - rm -rf src-tauri/target

  clean:web:
    desc: Clean web build artifacts only
    cmds:
      - rm -rf web/dist

  # ===== Check Tasks =====

  check:
    desc: Quick compile check
    cmds:
      - cd web && bun run typecheck

  check:all:
    desc: Run format check, lint, test, and build
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:web

  # ===== Workflow Tasks =====

  pre:commit:
    desc: Run checks before committing
    cmds:
      - task: fmt
      - task: test

  # ===== CI Tasks =====

  ci:
    desc: Run full CI pipeline
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:all

  # ===== Release Tasks =====

  release:patch:
    desc: Release a patch version (bug fixes)
    cmds:
      - task: fmt
      - task: test
      - task: version:bump
        vars:
          BUMP_TYPE: patch

  release:minor:
    desc: Release a minor version (new features)
    cmds:
      - task: fmt
      - task: test
      - task: version:bump
        vars:
          BUMP_TYPE: minor

  release:major:
    desc: Release a major version (breaking changes)
    cmds:
      - task: fmt
      - task: test
      - task: version:bump
        vars:
          BUMP_TYPE: major

  version:bump:
    desc: Bump version in all config files (internal task)
    internal: true
    vars:
      BUMP_TYPE: '{{.BUMP_TYPE}}'
    cmds:
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        case "{{.BUMP_TYPE}}" in
          patch) NEW_VERSION="$major.$minor.$((patch + 1))" ;;
          minor) NEW_VERSION="$major.$((minor + 1)).0" ;;
          major) NEW_VERSION="$((major + 1)).0.0" ;;
        esac
        echo "$NEW_VERSION" > VERSION
        
        # Update Cargo.toml version (matches: version = "x.y.z" under [package])
        awk -v ver="$NEW_VERSION" '/^version = "/{gsub(/version = "[^"]*"/, "version = \""ver"\"")}1' src-tauri/Cargo.toml > tmp && mv tmp src-tauri/Cargo.toml
        
        # Update tauri.conf.json version
        awk -v ver="$NEW_VERSION" '/"version":/{gsub(/"version": "[^"]*"/, "\"version\": \""ver"\"")}1' src-tauri/tauri.conf.json > tmp && mv tmp src-tauri/tauri.conf.json
        
        # Update web package.json version
        awk -v ver="$NEW_VERSION" '/"version":/{gsub(/"version": "[^"]*"/, "\"version\": \""ver"\"")}1' web/package.json > tmp && mv tmp web/package.json
        
        git add -A
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:publish:
    desc: Push commits and tags to remote (with safety checks)
    cmds:
      - |
        # Safety checks
        if [ -n "$(git status --porcelain)" ]; then
          echo "Error: Working tree is not clean. Commit or stash changes first."
          exit 1
        fi
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        if [ "$BRANCH" != "main" ]; then
          echo "Error: Not on main branch (currently on '$BRANCH'). Switch to main first."
          exit 1
        fi
        # Push commits and tags
        git push
        git push --tags
        echo "Published to remote successfully!"

  # ===== Utility Tasks =====

  version:
    desc: Show current version
    cmds:
      - cat VERSION

  version:show:
    desc: Show project information
    cmds:
      - |
        echo "pastel-hn - Hacker News Desktop Client"
        echo "Stack: TypeScript + Bun + Tauri"
        echo "Version: $(cat VERSION)"

  loc:count:
    desc: Count lines of code
    cmds:
      - |
        echo "=== pastel-hn LoC ==="
        echo ""
        echo "TypeScript:"
        find web/src -name "*.ts" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No TS files yet"
        echo ""
        echo "CSS:"
        find web/src -name "*.css" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No CSS files yet"

  icon:gen:
    desc: Generate app icons from SVG source
    dir: src-tauri/icons
    cmds:
      - |
        echo "Generating PNG icons from icon.svg..."
        
        # Standard sizes
        rsvg-convert -w 16 -h 16 icon.svg > 16x16.png
        rsvg-convert -w 32 -h 32 icon.svg > 32x32.png
        rsvg-convert -w 64 -h 64 icon.svg > 64x64.png
        rsvg-convert -w 128 -h 128 icon.svg > 128x128.png
        rsvg-convert -w 256 -h 256 icon.svg > 256x256.png
        rsvg-convert -w 512 -h 512 icon.svg > 512x512.png
        rsvg-convert -w 1024 -h 1024 icon.svg > icon.png
        
        # Retina sizes (@2x)
        rsvg-convert -w 32 -h 32 icon.svg > 16x16@2x.png
        rsvg-convert -w 64 -h 64 icon.svg > 32x32@2x.png
        rsvg-convert -w 256 -h 256 icon.svg > 128x128@2x.png
        rsvg-convert -w 512 -h 512 icon.svg > 256x256@2x.png
        
        echo "PNG icons generated!"
        
        # Generate .icns for macOS (requires iconutil)
        if command -v iconutil &> /dev/null; then
          echo "Generating icon.icns..."
          mkdir -p icon.iconset
          cp 16x16.png icon.iconset/icon_16x16.png
          cp 16x16@2x.png icon.iconset/icon_16x16@2x.png
          cp 32x32.png icon.iconset/icon_32x32.png
          cp 32x32@2x.png icon.iconset/icon_32x32@2x.png
          cp 128x128.png icon.iconset/icon_128x128.png
          cp 128x128@2x.png icon.iconset/icon_128x128@2x.png
          cp 256x256.png icon.iconset/icon_256x256.png
          cp 256x256@2x.png icon.iconset/icon_256x256@2x.png
          cp 512x512.png icon.iconset/icon_512x512.png
          cp icon.png icon.iconset/icon_512x512@2x.png
          iconutil -c icns icon.iconset -o icon.icns
          rm -rf icon.iconset
          echo "icon.icns generated!"
        else
          echo "Warning: iconutil not found, skipping .icns generation"
        fi
        
        # Generate .ico for Windows (requires ImageMagick convert)
        if command -v convert &> /dev/null; then
          echo "Generating icon.ico..."
          convert 16x16.png 32x32.png 64x64.png 128x128.png 256x256.png icon.ico
          echo "icon.ico generated!"
        else
          echo "Warning: ImageMagick not found, skipping .ico generation"
        fi
        
        echo "Icon generation complete!"

  install:tools:
    desc: Install development tools
    cmds:
      - |
        echo "Checking tools..."
        echo ""
        echo "Bun:"
        bun --version || echo "  Not installed - https://bun.sh"
        echo ""
        echo "Rust/Cargo (for Tauri):"
        cargo --version || echo "  Not installed - https://rustup.rs"
