version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===== Build Tasks =====

  build:web:
    desc: Build TypeScript/web frontend
    dir: web
    cmds:
      - bun run build

  build:tauri:
    desc: Build Tauri desktop app
    deps: [build:web]
    cmds:
      - cd src-tauri && cargo build --release

  build:all:
    desc: Build web and Tauri
    deps: [build:web, build:tauri]

  # ===== Test Tasks =====

  test:web:
    desc: Run TypeScript/web tests
    dir: web
    cmds:
      - bun run test:run

  test:e2e:
    desc: Run Playwright end-to-end tests
    deps: [build:web]
    cmds:
      - bunx playwright test

  test:
    desc: Run all tests
    cmds:
      - task: test:web

  # ===== Development Tasks =====

  dev:web:
    desc: Start web dev server with hot reload
    dir: web
    cmds:
      - bun run dev

  dev:tauri:
    desc: Start Tauri dev mode
    cmds:
      - cd src-tauri && cargo tauri dev

  dev:
    desc: Start development (alias for dev:tauri)
    cmds:
      - task: dev:tauri

  run:app:
    desc: Run the desktop app (debug mode, default)
    cmds:
      - cargo tauri dev

  run:app:debug:
    desc: Run the desktop app in debug mode (alias for run:app)
    cmds:
      - task: run:app

  run:app:release:
    desc: Build and run the desktop app in release mode
    deps: [build:web]
    cmds:
      - cd src-tauri && cargo build --release
      - ./src-tauri/target/release/pastel-hn

  # ===== Format & Lint Tasks =====

  fmt:web:
    desc: Format TypeScript/web code
    dir: web
    cmds:
      - bunx biome check --write --unsafe src/

  fmt:
    desc: Format all code
    cmds:
      - task: fmt:web

  fmt:check:
    desc: Check formatting (CI-friendly)
    cmds:
      - cd web && bunx biome check src/

  lint:
    desc: Lint all code
    cmds:
      - cd web && bunx biome lint src/

  # ===== Clean Tasks =====

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf web/dist
      - rm -rf src-tauri/target

  clean:web:
    desc: Clean web build artifacts only
    cmds:
      - rm -rf web/dist

  # ===== Check Tasks =====

  check:
    desc: Quick compile check
    cmds:
      - cd web && bun run typecheck

  check:all:
    desc: Run format check, lint, test, and build
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:web

  # ===== Workflow Tasks =====

  pre:commit:
    desc: Run checks before committing
    cmds:
      - task: fmt
      - task: test

  # ===== CI Tasks =====

  ci:
    desc: Run full CI pipeline
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:all

  # ===== Release Tasks =====

  release:patch:
    desc: Release a patch version (bug fixes)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$major.$minor.$((patch + 1))"
        echo "$NEW_VERSION" > VERSION
        git add -A
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:minor:
    desc: Release a minor version (new features)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$major.$((minor + 1)).0"
        echo "$NEW_VERSION" > VERSION
        git add -A
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:major:
    desc: Release a major version (breaking changes)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$((major + 1)).0.0"
        echo "$NEW_VERSION" > VERSION
        git add -A
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:publish:
    desc: Push commits and tags to remote (with safety checks)
    cmds:
      - |
        # Safety checks
        if [ -n "$(git status --porcelain)" ]; then
          echo "Error: Working tree is not clean. Commit or stash changes first."
          exit 1
        fi
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        if [ "$BRANCH" != "main" ]; then
          echo "Error: Not on main branch (currently on '$BRANCH'). Switch to main first."
          exit 1
        fi
        # Push commits and tags
        git push
        git push --tags
        echo "Published to remote successfully!"

  # ===== Utility Tasks =====

  version:
    desc: Show current version
    cmds:
      - cat VERSION

  version:show:
    desc: Show project information
    cmds:
      - |
        echo "pastel-hn - Hacker News Desktop Client"
        echo "Stack: TypeScript + Bun + Tauri"
        echo "Version: $(cat VERSION)"

  loc:count:
    desc: Count lines of code
    cmds:
      - |
        echo "=== pastel-hn LoC ==="
        echo ""
        echo "TypeScript:"
        find web/src -name "*.ts" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No TS files yet"
        echo ""
        echo "CSS:"
        find web/src -name "*.css" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No CSS files yet"

  install:tools:
    desc: Install development tools
    cmds:
      - |
        echo "Checking tools..."
        echo ""
        echo "Bun:"
        bun --version || echo "  Not installed - https://bun.sh"
        echo ""
        echo "Rust/Cargo (for Tauri):"
        cargo --version || echo "  Not installed - https://rustup.rs"
