version: "3"

vars:
  SHELL: bash
  ZIG_VERSION: "0.15"
  WASM_OUT: "web/public/hn.wasm"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===== Build Tasks =====

  build:wasm:
    desc: Build hn.wasm (ReleaseSmall - optimized for size)
    cmds:
      - zig build --release=small
      - mkdir -p web/public
      - cp zig-out/bin/hn.wasm {{.WASM_OUT}}

  build:wasm:fast:
    desc: Build hn.wasm (ReleaseFast - optimized for speed)
    cmds:
      - zig build --release=fast
      - mkdir -p web/public
      - cp zig-out/bin/hn.wasm {{.WASM_OUT}}

  build:wasm:debug:
    desc: Build hn.wasm (Debug - with debug info)
    cmds:
      - zig build
      - mkdir -p web/public
      - cp zig-out/bin/hn.wasm {{.WASM_OUT}}

  build:web:
    desc: Build TypeScript/web frontend
    dir: web
    cmds:
      - bun run build

  build:tauri:
    desc: Build Tauri desktop app
    deps: [build:wasm, build:web]
    cmds:
      - cd src-tauri && cargo build --release

  build:all:
    desc: Build WASM, web, and Tauri
    deps: [build:wasm, build:web, build:tauri]

  # ===== Test Tasks =====

  test:zig:
    desc: Run Zig unit tests
    cmds:
      - zig build test

  test:web:
    desc: Run TypeScript/web tests
    dir: web
    cmds:
      - bun test

  test:e2e:
    desc: Run Playwright end-to-end tests
    deps: [build:wasm, build:web]
    cmds:
      - bunx playwright test

  test:
    desc: Run all tests
    cmds:
      - task: test:zig
      - task: test:web

  # ===== Development Tasks =====

  dev:web:
    desc: Start web dev server with hot reload
    deps: [build:wasm]
    dir: web
    cmds:
      - bun run dev

  dev:tauri:
    desc: Start Tauri dev mode
    deps: [build:wasm]
    cmds:
      - cd src-tauri && cargo tauri dev

  dev:
    desc: Start development (alias for dev:tauri)
    cmds:
      - task: dev:tauri

  run:app:
    desc: Build and run the desktop app
    deps: [build:wasm]
    cmds:
      - mkdir -p web/public && cp zig-out/bin/hn.wasm web/public/
      - cargo tauri dev

  # ===== Format & Lint Tasks =====

  fmt:zig:
    desc: Format Zig code
    cmds:
      - zig fmt src/

  fmt:web:
    desc: Format TypeScript/web code
    dir: web
    cmds:
      - bunx biome check --write --unsafe src/

  fmt:
    desc: Format all code
    cmds:
      - task: fmt:zig
      - task: fmt:web

  fmt:check:
    desc: Check formatting (CI-friendly)
    cmds:
      - zig fmt --check src/
      - cd web && bunx biome check src/

  lint:
    desc: Lint all code
    cmds:
      - zig build --release=small
      - cd web && bunx biome lint src/

  # ===== Clean Tasks =====

  clean:
    desc: Clean all build artifacts
    cmds:
      - rm -rf zig-out .zig-cache
      - rm -rf web/dist web/public/hn.wasm
      - rm -rf src-tauri/target

  clean:wasm:
    desc: Clean WASM build artifacts only
    cmds:
      - rm -rf zig-out .zig-cache
      - rm -f {{.WASM_OUT}}

  # ===== Check Tasks =====

  check:
    desc: Quick compile check
    cmds:
      - zig build --release=small
      - cd web && bun run typecheck

  check:all:
    desc: Run format check, lint, test, and build
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:wasm

  # ===== TDD & Workflow Tasks =====

  pre:commit:
    desc: Run checks before committing (TDD workflow)
    cmds:
      - task: fmt
      - task: test

  tdd:
    desc: TDD cycle - watch mode
    cmds:
      - |
        if command -v watchexec &> /dev/null; then
          watchexec -e zig task test:zig
        else
          echo "Install watchexec for watch mode: cargo install watchexec-cli"
          echo "Running tests once..."
          task test:zig
        fi

  # ===== CI Tasks =====

  ci:
    desc: Run full CI pipeline
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build:all

  # ===== Release Tasks =====

  release:patch:
    desc: Release a patch version (bug fixes)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$major.$minor.$((patch + 1))"
        echo "$NEW_VERSION" > VERSION
        git add VERSION
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:minor:
    desc: Release a minor version (new features)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$major.$((minor + 1)).0"
        echo "$NEW_VERSION" > VERSION
        git add VERSION
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  release:major:
    desc: Release a major version (breaking changes)
    cmds:
      - task: fmt
      - task: test
      - |
        VERSION=$(cat VERSION)
        IFS='.' read -r major minor patch <<< "$VERSION"
        NEW_VERSION="$((major + 1)).0.0"
        echo "$NEW_VERSION" > VERSION
        git add VERSION
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        echo "Released v$NEW_VERSION - run 'git push --tags' to publish"

  # ===== Utility Tasks =====

  version:
    desc: Show current version
    cmds:
      - cat VERSION

  version:show:
    desc: Show project information
    cmds:
      - |
        echo "wasm-hn - Hacker News Desktop Client"
        echo "Stack: Zig/WASM + TypeScript + Tauri"
        echo "Zig: {{.ZIG_VERSION}}+"
        cat VERSION 2>/dev/null && echo "" || echo "Version: 0.1.0"

  loc:count:
    desc: Count lines of code
    cmds:
      - |
        echo "=== wasm-hn LoC ==="
        echo "Zig:"
        find src -name "*.zig" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No Zig files yet"
        echo ""
        echo "TypeScript:"
        find web/src -name "*.ts" 2>/dev/null | xargs wc -l 2>/dev/null || echo "  No TS files yet"

  install:tools:
    desc: Install development tools
    cmds:
      - |
        echo "Checking tools..."
        echo ""
        echo "Zig:"
        zig version || echo "  Not installed - https://ziglang.org/download/"
        echo ""
        echo "Bun:"
        bun --version || echo "  Not installed - https://bun.sh"
        echo ""
        echo "Rust/Cargo (for Tauri):"
        cargo --version || echo "  Not installed - https://rustup.rs"
        echo ""
        echo "Optional: watchexec for TDD"
        watchexec --version 2>/dev/null || echo "  cargo install watchexec-cli"
